// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Comment struct {
	ID        string     `json:"id"`
	Text      string     `json:"text"`
	Post      *Post      `json:"post"`
	Author    *User      `json:"author"`
	Children  []*Comment `json:"children"`
	CreatedAt string     `json:"createdAt"`
}

type CommentInput struct {
	Text     string  `json:"text"`
	PostID   string  `json:"postId"`
	AuthorID string  `json:"authorId"`
	ParentID *string `json:"parentId,omitempty"`
}

type Mutation struct {
}

type Post struct {
	ID            string     `json:"id"`
	Title         string     `json:"title"`
	Content       string     `json:"content"`
	Author        *User      `json:"author"`
	AllowComments bool       `json:"allowComments"`
	Comments      []*Comment `json:"comments"`
}

type PostInput struct {
	Title         string `json:"title"`
	Content       string `json:"content"`
	AuthorID      string `json:"authorId"`
	AllowComments bool   `json:"allowComments"`
}

type Query struct {
}

type Subscription struct {
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type UserInput struct {
	Name string `json:"name"`
}
